name: WorldEditTest
description: Mines like Prison
author: Mackenzie Molloy
version: 1.0
main: net.mackenziemolloy.WorldEditTest.WorldEditTest
api-version: 1.16
depend: [WorldEdit]
commands:
  wet:
    description: "World Edit Test Command"